# Generated by Django 4.2.3 on 2023-07-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_activity_activities_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='msg',
            field=models.TextField(),
        ),
    ]
