# Generated by Django 4.2.3 on 2023-08-03 01:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_chat_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatMessage',
        ),
        migrations.RenameModel(
            old_name='TravelPlans',
            new_name='TravelPlan',
        ),
    ]
