# Generated by Django 4.2.3 on 2023-08-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_activities_activity_rename_chat_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='function_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
