# Generated by Django 4.2.3 on 2023-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessage_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
