# Generated by Django 4.2.3 on 2023-08-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_travelplan_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelplan',
            options={'ordering': ['last_modified']},
        ),
        migrations.AddField(
            model_name='travelplan',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
