# Generated by Django 4.2.3 on 2023-08-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_travelplan_options_travelplan_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.URLField(),
        ),
    ]
